# Generated by Django 3.2.10 on 2021-12-14 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon_api', '0003_auto_20211202_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
